apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactjs-app
  template:
    metadata:
      labels:
        app: reactjs-app
    spec:
      imagePullSecrets:
      - name: ecr-creds   # <-- important
      containers:
      - name: reactjs-app
        image: 423623845359.dkr.ecr.us-east-1.amazonaws.com/reactjs-app-k8:360036df75285af6619f4cb38d895ae4a684b1fe
        ports:
        - containerPort: 9000
