apiVersion: v1
kind: Service
metadata:
  name: reactjs-app-service
spec:
  type: NodePort
  selector:
    app: reactjs-app
  ports:
    - port: 9000          # Port to access inside the cluster
      targetPort: 9000    # Port your container listens on (from Dockerfile)
      nodePort: 30900     # External port to access from browser (your choice between 30000–32767)
