name: CI/CD for React App with ECR and Argo CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build Docker Image, Push to ECR, and Trigger ArgoCD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}
          docker build -t $IMAGE_URI .
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Push Docker image to Amazon ECR
        run: docker push $IMAGE_URI

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Update Kubernetes Deployment manifest with new image
        run: |
          sed -i "s|image:.*|image: $IMAGE_URI|g" k8s/deployment.yaml
          git add k8s/deployment.yaml
          git commit -m "ci: update image to $IMAGE_URI" || echo "No changes to commit"

      - name: Push changes to GitHub
        run: git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }} HEAD:main

